import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// 1 MYR token = 1 Malaysian Ringgit. We price it against the live ETH/MYR rate
// so buying 1 MYR costs the ETH-equivalent of RM 1.
async function fetchLiveEthMyr(): Promise<number> {
  try {
    const res = await fetch(
      "https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=myr",
      { signal: AbortSignal.timeout(5000) }
    );
    if (!res.ok) throw new Error(`CoinGecko ${res.status}`);
    const data = await res.json() as { ethereum: { myr: number } };
    const price = Math.round(data.ethereum.myr);
    if (price > 0) return price;
  } catch (e) {
    console.warn("Could not fetch live price:", e instanceof Error ? e.message : e);
  }
  console.warn("Falling back to hardcoded price: RM 18,000 / ETH");
  return 18_000;
}

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying ICO with account:", deployer.address);

  // ETH/MYR rate → price in wei per 1 whole MYR token (= value of RM 1 in ETH).
  const ethMyr = await fetchLiveEthMyr();
  const PRICE_WEI = ethers.parseEther("1") / BigInt(ethMyr);
  console.log(`Rate: 1 ETH = RM ${ethMyr.toLocaleString()} → 1 MYR = ${ethers.formatEther(PRICE_WEI)} ETH`);

  // 1. Deploy the MYR token (full supply minted to deployer)
  const Token = await ethers.getContractFactory("RinggitToken");
  const token = await Token.deploy();
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();

  // 2. Deploy the ICO pointed at the token
  const ICO = await ethers.getContractFactory("ICO");
  const ico = await ICO.deploy(tokenAddress, PRICE_WEI);
  await ico.waitForDeployment();
  const icoAddress = await ico.getAddress();

  // 3. Owner approves the ICO to sell the entire supply
  const totalSupply = await token.totalSupply();
  const approveTx = await token.approve(icoAddress, totalSupply);
  await approveTx.wait();

  console.log("RinggitToken (MYR) deployed to:", tokenAddress);
  console.log("ICO            deployed to:", icoAddress);
  console.log("Price: 1 MYR = RM 1 =", ethers.formatEther(PRICE_WEI), "ETH");
  console.log("Owner approved ICO for:", ethers.formatUnits(totalSupply, 18), "MYR\n");

  // 4. Write a self-contained config for the Next.js frontend (addresses + ABIs)
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const tokenArtifact = require("../artifacts/contracts/RinggitToken.sol/RinggitToken.json");
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const icoArtifact = require("../artifacts/contracts/ICO.sol/ICO.json");

  const outputPath = path.join(__dirname, "../../src/lib/icoConfig.ts");
  const content = `// !! Auto-generated by blockchain/scripts/deploy-ico.ts — do not edit manually !!
// Re-run: npm run deploy:ico

export const ICO_ADDRESSES = {
  RinggitToken: "${tokenAddress}",
  ICO:          "${icoAddress}",
} as const;

export const ICO_PRICE_WEI = "${PRICE_WEI.toString()}";

// ETH/MYR rate used at deploy time (1 MYR token = RM 1).
export const ICO_ETH_MYR = ${ethMyr};

export const RINGGIT_TOKEN_ABI = ${JSON.stringify(tokenArtifact.abi, null, 2)} as const;

export const ICO_ABI = ${JSON.stringify(icoArtifact.abi, null, 2)} as const;
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content);
  console.log("ICO config written to:", outputPath);
  console.log("\nNext: open http://localhost:3000/ico, connect MetaMask, and buy MYR.");
  console.log("Import the MYR token in MetaMask using:", tokenAddress);
}

main().catch(e => { console.error(e); process.exitCode = 1; });
