import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  // Deploy CryptoLoan — constructor also deploys MockMYR internally
  // Initial ETH price: RM 18,000 (approximate MYR value)
  const CryptoLoan = await ethers.getContractFactory("CryptoLoan");
  const loan = await CryptoLoan.deploy(18000);
  await loan.waitForDeployment();

  const loanAddress = await loan.getAddress();
  const myrAddress  = await loan.myr();

  console.log("CryptoLoan deployed to:", loanAddress);
  console.log("MockMYR    deployed to:", myrAddress);
  console.log("ETH price set to:       RM 18,000\n");

  // Load ABIs from compiled artifacts
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const loanArtifact = require("../artifacts/contracts/CryptoLoan.sol/CryptoLoan.json");
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const myrArtifact  = require("../artifacts/contracts/MockMYR.sol/MockMYR.json");

  // Write contractConfig.ts for the Next.js frontend
  const outputPath = path.join(__dirname, "../../src/lib/contractConfig.ts");
  const content = `// !! Auto-generated by blockchain/scripts/deploy.ts — do not edit manually !!
// Re-run: npm run deploy:local

export const HARDHAT_CHAIN_ID = 31337;
export const HARDHAT_RPC_URL  = "http://127.0.0.1:8545";
export const ETH_PRICE_MYR    = 18000;

export const CONTRACT_ADDRESSES = {
  CryptoLoan: "${loanAddress}",
  MockMYR:    "${myrAddress}",
} as const;

export const CRYPTO_LOAN_ABI = ${JSON.stringify(loanArtifact.abi, null, 2)} as const;

export const MOCK_MYR_ABI = ${JSON.stringify(myrArtifact.abi, null, 2)} as const;
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content);
  console.log("Contract config written to:", outputPath);

  console.log("\n── First 3 Hardhat test accounts ─────────────────────────────");
  const signers = await ethers.getSigners();
  for (let i = 0; i < Math.min(3, signers.length); i++) {
    console.log(`Account #${i}: ${signers[i].address}`);
  }
  console.log("Private keys are printed when you run 'npm run chain'.\n");
  console.log("Next steps:");
  console.log("  1. Add Hardhat network to MetaMask (RPC: http://127.0.0.1:8545, Chain ID: 31337)");
  console.log("  2. Import an account using a private key from 'npm run chain' output");
  console.log("  3. Open http://localhost:3000 and click 'Connect Wallet'");
}

main().catch(e => { console.error(e); process.exitCode = 1; });
