import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function fetchLiveEthMyr(): Promise<number> {
  try {
    const res = await fetch(
      "https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=myr",
      { signal: AbortSignal.timeout(5000) }
    );
    if (!res.ok) throw new Error(`CoinGecko ${res.status}`);
    const data = await res.json() as { ethereum: { myr: number } };
    const price = Math.round(data.ethereum.myr);
    if (price > 0) return price;
  } catch (e) {
    console.warn("Could not fetch live price:", e instanceof Error ? e.message : e);
  }
  console.warn("Falling back to hardcoded price: RM 18,000");
  return 18_000;
}

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  // Contract addresses are derived from (deployer, nonce). Deploying on a node
  // that already has transactions advances the nonce, so CryptoLoan — and the
  // MockMYR it creates in its constructor — land at *new* addresses every time.
  // MetaMask keys tokens by address, so each such redeploy adds yet another
  // duplicate "MYR" token to the user's wallet. Requiring a fresh node (nonce 0)
  // keeps both addresses constant across redeploys, so there is only ever one MYR.
  const nonce = await ethers.provider.getTransactionCount(deployer.address);
  if (nonce !== 0 && process.env.FORCE_DEPLOY !== "1") {
    console.error(
      `\n✗ Node is not fresh — deployer nonce is ${nonce}, expected 0.\n` +
      `  Redeploying now would place MockMYR at a NEW address and add another\n` +
      `  duplicate "MYR" token in MetaMask.\n\n` +
      `  Fix: restart the Hardhat node, then deploy as the first action:\n` +
      `    1) Stop the running node, then:  npm run chain\n` +
      `    2) In a second terminal:         npm run deploy:local\n\n` +
      `  This keeps the MYR address constant. To deploy anyway (and accept a new\n` +
      `  token address), re-run with FORCE_DEPLOY=1.\n`
    );
    process.exitCode = 1;
    return;
  }

  // Fetch live price so the contract starts in sync with the market
  console.log("Fetching live ETH/MYR price from CoinGecko…");
  const ethPrice = await fetchLiveEthMyr();
  console.log(`Initial ETH price: RM ${ethPrice.toLocaleString()}\n`);

  // Deploy CryptoLoan — constructor also deploys MockMYR internally
  const CryptoLoan = await ethers.getContractFactory("CryptoLoan");
  const loan = await CryptoLoan.deploy(ethPrice);
  await loan.waitForDeployment();

  const loanAddress = await loan.getAddress();
  const myrAddress  = await loan.myr();

  console.log("CryptoLoan deployed to:", loanAddress);
  console.log("MockMYR    deployed to:", myrAddress);
  console.log(`ETH price set to:       RM ${ethPrice.toLocaleString()}\n`);

  // Load ABIs from compiled artifacts
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const loanArtifact = require("../artifacts/contracts/CryptoLoan.sol/CryptoLoan.json");
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const myrArtifact  = require("../artifacts/contracts/MockMYR.sol/MockMYR.json");

  // Write contractConfig.ts for the Next.js frontend
  const outputPath = path.join(__dirname, "../../src/lib/contractConfig.ts");
  const content = `// !! Auto-generated by blockchain/scripts/deploy.ts — do not edit manually !!
// Re-run: npm run deploy:local

export const HARDHAT_CHAIN_ID = 31337;
export const HARDHAT_RPC_URL  = "http://127.0.0.1:8545";
export const ETH_PRICE_MYR    = ${ethPrice};

export const CONTRACT_ADDRESSES = {
  CryptoLoan: "${loanAddress}",
  MockMYR:    "${myrAddress}",
} as const;

export const CRYPTO_LOAN_ABI = ${JSON.stringify(loanArtifact.abi, null, 2)} as const;

export const MOCK_MYR_ABI = ${JSON.stringify(myrArtifact.abi, null, 2)} as const;
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content);
  console.log("Contract config written to:", outputPath);

  console.log("\n── First 3 Hardhat test accounts ─────────────────────────────");
  const signers = await ethers.getSigners();
  for (let i = 0; i < Math.min(3, signers.length); i++) {
    console.log(`Account #${i}: ${signers[i].address}`);
  }
  console.log("Private keys are printed when you run 'npm run chain'.\n");
  console.log("Next steps:");
  console.log("  1. Add Hardhat network to MetaMask (RPC: http://127.0.0.1:8545, Chain ID: 31337)");
  console.log("  2. Import an account using a private key from 'npm run chain' output");
  console.log("  3. Open http://localhost:3000 and click 'Connect Wallet'");
}

main().catch(e => { console.error(e); process.exitCode = 1; });
